#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Alpha_Game_State

#include "Basic.hpp"

#include "ST_Custom_Team_Structure_renamed_structs.hpp"
#include "Engine_structs.hpp"
#include "ST_Team_Strucutre_Info_renamed_structs.hpp"
#include "E_Items_structs.hpp"
#include "ST_ServerHostSettings_renamed_2_structs.hpp"
#include "E_GameModes_structs.hpp"
#include "ST_InventoryArray_renamed_structs.hpp"
#include "E_ShipTypes_structs.hpp"
#include "E_Tiers_structs.hpp"
#include "BP_GameState_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Alpha_Game_State.Alpha_Game_State_C
// 0x0300 (0x0688 - 0x0388)
class AAlpha_Game_State_C : public ABP_GameState_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Alpha_Game_State_C;                 // 0x0388(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTODManager_C*                          TODManager;                                        // 0x0390(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FST_ServerHostSettings_renamed_2       Server_Host_Settings;                              // 0x0398(0x0090)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	TArray<class ANewTeamManager_C*>              TeamManagers;                                      // 0x0428(0x0010)(Edit, BlueprintVisible, Net, DisableEditOnTemplate, DisableEditOnInstance, RepNotify)
	TArray<class ABP_BoatSpawn_C*>                Ship_Spawn_Points;                                 // 0x0438(0x0010)(Edit, BlueprintVisible, Net, DisableEditOnTemplate, DisableEditOnInstance)
	int32                                         Total_Team_Count;                                  // 0x0448(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Total_Ship_Count;                                  // 0x044C(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Total_Player_Count;                                // 0x0450(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Remaining_Team_Count;                              // 0x0454(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Remaining_Ship_Count;                              // 0x0458(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Remaining_Player_Count;                            // 0x045C(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Winning_Team_ID;                                   // 0x0460(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_GameModes                                   GameMode;                                          // 0x0464(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_465[0x3];                                      // 0x0465(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Session_Time;                                      // 0x0468(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Started_Session_Time;                              // 0x046C(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Start_Timer;                                       // 0x0470(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         End_Timer;                                         // 0x0474(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          GameOver;                                          // 0x0478(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Spawn_Loot_Chest_On_Player_Death;                  // 0x0479(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Spawn_Weapons_On_Player_Death;                     // 0x047A(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Spawn_Weapons_On_Player_Defeat;                    // 0x047B(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Pre_Game;                                          // 0x047C(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_47D[0x3];                                      // 0x047D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         Rewarded_Ids;                                      // 0x0480(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          Client_Hosted_Custom_Game;                         // 0x0490(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_491[0x7];                                      // 0x0491(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FUniqueNetIdRepl                       Client_Hosted_ID;                                  // 0x0498(0x0028)(Edit, BlueprintVisible, Net, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          Fleet_Mode_To_Be_Reworked;                         // 0x04C0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4C1[0x7];                                      // 0x04C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FST_Team_Strucutre_Info_renamed> Team_Structure_Info;                              // 0x04C8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         Match_Making_Player_Count;                         // 0x04D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Has_Set_Team_Structure_Info;                       // 0x04DC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4DD[0x3];                                      // 0x04DD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FST_Team_Strucutre_Info_renamed> Team_Unique_Id_Structure_Info;                    // 0x04E0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          Can_Change_Team;                                   // 0x04F0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4F1[0x3];                                      // 0x04F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   Next_Level;                                        // 0x04F4(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Load_Next_Level;                                   // 0x04FC(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4FD[0x3];                                      // 0x04FD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<E_ShipTypes>                           Available_Ship_Types;                              // 0x0500(0x0010)(Edit, BlueprintVisible, Net, DisableEditOnInstance)
	int32                                         Max_Crew_Sloop;                                    // 0x0510(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Prevent_AFK;                                       // 0x0514(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_515[0x3];                                      // 0x0515(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              Teams_Updated;                                     // 0x0518(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          Friendly_Fire;                                     // 0x0528(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Spawn_Ships;                                       // 0x0529(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Ship_Damage_on_Collision_;                         // 0x052A(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_52B[0x1];                                      // 0x052B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Max_Ship_Hole_Damage;                              // 0x052C(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Ship_Flow_Rate_Multiplier;                         // 0x0530(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Default_Main_Weapon;                               // 0x0534(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Default_Side_Arm_Weapon;                           // 0x0538(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Default_Melee_Weapon;                              // 0x053C(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMap<E_Items, int32>                          Default_Ship_Inventory;                            // 0x0540(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         Default_Ship_Cannon_Level;                         // 0x0590(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Default_Ship_Capstan_Level;                        // 0x0594(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Default_Ship_Pump_Level;                           // 0x0598(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Default_Ship_Steering_Level;                       // 0x059C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Deadzone_Spawn;                                    // 0x05A0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Deadzone_Pause;                                    // 0x05A1(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5A2[0x6];                                      // 0x05A2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 Deadzone_Scales;                                   // 0x05A8(0x0010)(Edit, BlueprintVisible, Net, DisableEditOnInstance)
	TArray<int32>                                 Deadzone_Wait_Times;                               // 0x05B8(0x0010)(Edit, BlueprintVisible, Net, DisableEditOnInstance)
	TArray<int32>                                 Deadzone_Close_Times;                              // 0x05C8(0x0010)(Edit, BlueprintVisible, Net, DisableEditOnInstance)
	TArray<int32>                                 Deadzone_Damage_Scales;                            // 0x05D8(0x0010)(Edit, BlueprintVisible, Net, DisableEditOnInstance)
	bool                                          Deadzone_Instant_Kill;                             // 0x05E8(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Deadzone_Final_Island_Spawn;                       // 0x05E9(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          Deadzone_Center_To_Map;                            // 0x05EA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5EB[0x1];                                      // 0x05EB(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Default_Ship_Swivel_Amount;                        // 0x05EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Enable_Vote_Kick;                                  // 0x05F0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5F1[0x3];                                      // 0x05F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Max_Players;                                       // 0x05F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Default_Inventory_Size;                            // 0x05F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5FC[0x4];                                      // 0x05FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FST_InventoryArray_renamed>     Default_Inventory;                                 // 0x0600(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<struct FST_Custom_Team_Structure_renamed> Custom_Team_Structure_Info;                     // 0x0610(0x0010)(Edit, BlueprintVisible, Net, DisableEditOnInstance)
	class FString                                 Team_Formation_String;                             // 0x0620(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class UClass*                                 Character_Class;                                   // 0x0630(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Use_Incremental_Respawn_Time;                      // 0x0638(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_639[0x3];                                      // 0x0639(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Default_Respawn_Time;                              // 0x063C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Pre_Game_Sound;                                    // 0x0640(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Game_Sound;                                        // 0x0648(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Start_Game_Sound;                                  // 0x0650(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Setup_Character_on_Spawn;                          // 0x0658(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_659[0x7];                                      // 0x0659(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UClass*>                         Weapons_To_Remove_From_Spawn;                      // 0x0660(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class UClass*>                         Upgrades_To_Remove_From_Spawn;                     // 0x0670(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	E_Tiers                                       Global_Min_Tier;                                   // 0x0680(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_681[0x3];                                      // 0x0681(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Spawn_Protection_Time;                             // 0x0684(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Alpha_Game_State(int32 EntryPoint);
	void Set_Discord_Data();
	void Set_Server_Host_Settings(const struct FST_ServerHostSettings_renamed_2& Server_Host_Settings_0);
	void Load_Server_Host_Settings();
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void Print_Team_Info();
	void Make_New_Team(class ANewTeamManager_C* Team);
	void Custom_GetServerWorldTimeSeconds(float* ServerTime);
	void Find_Team_For_Player(const class FString& Player_Platform_ID, const struct FUniqueNetIdRepl& Player_ID, int32* Team_ID, int32* Crew_ID, bool* Found_Team);
	void Get_Available_Team_ID(int32* Available_Team_ID);
	void OnRep_Total_Team_Count();
	void Get_Filtered_Team_List(const struct FUniqueNetIdRepl& Unique_Net_Id, bool Pre_Made_Team_Check, TArray<class ANewTeamManager_C*>* Available_Teams);
	void Reset_Data();
	void Find_Team(int32 TeamID, class ANewTeamManager_C** Team, bool* Found);
	void Find_Crew(int32 TeamID, int32 CrewID, class ANewCrewManager_C** Crew, bool* Found, class UTeam_Crew_Ship_Member_State_C** Team_Crew_Ship_Member_State);
	void OnRep_TeamManagers();
	void Parse_Team_Structure(const class FString& Formation);
	void Parse_Crew_Structure(const class FString& Formation, struct FST_Custom_Team_Structure_renamed* Crews_Info);
	void Parse_Sub_Crew_Structure(const class FString& Formation, bool Is_N_size, struct FST_Custom_Team_Structure_renamed* Team_Structure);
	void Get_Team_Crew_Size_Info(int32 Team_ID, TArray<int32>* Crew_Sizes, bool* Is_N_Sized_Crew);
	void Get_Character_Class(class AAlpha_PlayerController_C* Controller_Ref, class UClass** Character_Class_0);
	void Get_Starting_Inventory(class AAlpha_PlayerController_C* Controller_Ref, TArray<struct FST_InventoryArray_renamed>* Inventory, int32* Inventory_Size);
	void Get_Ship_Inventory(class ANewShipManager_C* Ship_Manager_Ref, TMap<E_Items, int32>* Default_Ship_Inventory_0);
	void Get_Setup_Character_On_Spawn(class AAlpha_PlayerController_C* Controller_Ref, bool* Setup_Character_on_Spawn_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Alpha_Game_State_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Alpha_Game_State_C")
	}
	static class AAlpha_Game_State_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAlpha_Game_State_C>();
	}
};
DUMPER7_ASSERTS_AAlpha_Game_State_C;

SDK_NAMESPACE_END
