#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionChangeMaxPreGame

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_ActionChangeMaxPreGame.BP_ActionChangeMaxPreGame_C.ExecuteUbergraph_BP_ActionChangeMaxPreGame
// 0x0020 (0x0020 - 0x0000)
struct BP_ActionChangeMaxPreGame_C_ExecuteUbergraph_BP_ActionChangeMaxPreGame final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_StringToInt_ReturnValue;             // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_ActionChangeMaxPreGame_C_ExecuteUbergraph_BP_ActionChangeMaxPreGame;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
