#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionForceEndGame

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ActionBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ActionForceEndGame.BP_ActionForceEndGame_C
// 0x0010 (0x0270 - 0x0260)
class ABP_ActionForceEndGame_C final : public ABP_ActionBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_ActionForceEndGame_C;            // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          NotificationSound;                                 // 0x0268(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	void ExecuteUbergraph_BP_ActionForceEndGame(int32 EntryPoint);
	void Start_Action_Validated();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ActionForceEndGame_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ActionForceEndGame_C")
	}
	static class ABP_ActionForceEndGame_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ActionForceEndGame_C>();
	}
};
DUMPER7_ASSERTS_ABP_ActionForceEndGame_C;

SDK_NAMESPACE_END
