#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionGunGameLevelUp

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ActionBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ActionGunGameLevelUp.BP_ActionGunGameLevelUp_C
// 0x0008 (0x0268 - 0x0260)
class ABP_ActionGunGameLevelUp_C final : public ABP_ActionBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_ActionGunGameLevelUp_C;          // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_ActionGunGameLevelUp(int32 EntryPoint);
	void Start_Action_Validated();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ActionGunGameLevelUp_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ActionGunGameLevelUp_C")
	}
	static class ABP_ActionGunGameLevelUp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ActionGunGameLevelUp_C>();
	}
};
DUMPER7_ASSERTS_ABP_ActionGunGameLevelUp_C;

SDK_NAMESPACE_END
