#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ArmorPlateSlot

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_ArmorPlateSlot.BP_ArmorPlateSlot_C.ExecuteUbergraph_BP_ArmorPlateSlot
// 0x0004 (0x0004 - 0x0000)
struct BP_ArmorPlateSlot_C_ExecuteUbergraph_BP_ArmorPlateSlot final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_ArmorPlateSlot_C_ExecuteUbergraph_BP_ArmorPlateSlot;

// Function BP_ArmorPlateSlot.BP_ArmorPlateSlot_C.damage
// 0x000C (0x000C - 0x0000)
struct BP_ArmorPlateSlot_C_damage final
{
public:
	int32                                         DamageAmount;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_ArmorPlateSlot_C_damage;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
