#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionCommand_AddCOnquestInfo

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ActionBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ActionCommand_AddCOnquestInfo.BP_ActionCommand_AddCOnquestInfo_C
// 0x0030 (0x0290 - 0x0260)
class ABP_ActionCommand_AddCOnquestInfo_C final : public ABP_ActionBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_ActionCommand_AddCOnquestInfo_C; // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<class FString>                         CommandList;                                       // 0x0268(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FString                                 testlist;                                          // 0x0278(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class UUI_Chat_C*                             ChatRef;                                           // 0x0288(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ActionCommand_AddCOnquestInfo(int32 EntryPoint);
	void Start_Action_Unvalidated();
	void GetListOfCommands(class FString* List);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ActionCommand_AddCOnquestInfo_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ActionCommand_AddCOnquestInfo_C")
	}
	static class ABP_ActionCommand_AddCOnquestInfo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ActionCommand_AddCOnquestInfo_C>();
	}
};
DUMPER7_ASSERTS_ABP_ActionCommand_AddCOnquestInfo_C;

SDK_NAMESPACE_END
