#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionUnlockCrewSize

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_ActionUnlockCrewSize.BP_ActionUnlockCrewSize_C.ExecuteUbergraph_BP_ActionUnlockCrewSize
// 0x0018 (0x0018 - 0x0000)
struct BP_ActionUnlockCrewSize_C_ExecuteUbergraph_BP_ActionUnlockCrewSize final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_PlayerState_C*                      K2Node_DynamicCast_AsBP_Player_State;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_ActionUnlockCrewSize_C_ExecuteUbergraph_BP_ActionUnlockCrewSize;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
