#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AOEBase

#include "Basic.hpp"

#include "BP_AOEBase_classes.hpp"
#include "BP_AOEBase_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_AOEBase.BP_AOEBase_C.ExecuteUbergraph_BP_AOEBase
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AOEBase_C::ExecuteUbergraph_BP_AOEBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AOEBase_C", "ExecuteUbergraph_BP_AOEBase");

	Params::BP_AOEBase_C_ExecuteUbergraph_BP_AOEBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AOEBase.BP_AOEBase_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_AOEBase_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AOEBase_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AOEBase.BP_AOEBase_C.CheckIfBehindObstacle
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Character_C*                  Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   CanBeDamaged                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_AOEBase_C::CheckIfBehindObstacle(class ABP_Character_C* Character, bool* CanBeDamaged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AOEBase_C", "CheckIfBehindObstacle");

	Params::BP_AOEBase_C_CheckIfBehindObstacle Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);

	if (CanBeDamaged != nullptr)
		*CanBeDamaged = Parms.CanBeDamaged;
}


// Function BP_AOEBase.BP_AOEBase_C.CalculateDamage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AOEBase_C::CalculateDamage(const struct FVector& Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AOEBase_C", "CalculateDamage");

	Params::BP_AOEBase_C_CalculateDamage Parms{};

	Parms.Location = std::move(Location);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
