#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ArmorPlateSlot

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ArmorPlateSlot.BP_ArmorPlateSlot_C
// 0x0028 (0x0248 - 0x0220)
class ABP_ArmorPlateSlot_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Mesh;                                              // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          Active;                                            // 0x0238(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)
	uint8                                         Pad_239[0x3];                                      // 0x0239(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Health;                                            // 0x023C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_BoatMeshBase_C*                     ShipRef;                                           // 0x0240(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ArmorPlateSlot(int32 EntryPoint);
	void NoHighlight();
	void HighLight();
	void ReceiveBeginPlay();
	void OnRep_Active();
	void damage(int32 DamageAmount);
	void SetActive();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ArmorPlateSlot_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ArmorPlateSlot_C")
	}
	static class ABP_ArmorPlateSlot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ArmorPlateSlot_C>();
	}
};
DUMPER7_ASSERTS_ABP_ArmorPlateSlot_C;

SDK_NAMESPACE_END
