#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionShrinkToSmallestCircleDeathZone

#include "Basic.hpp"

#include "BP_ActionShrinkToSmallestCircleDeathZone_classes.hpp"
#include "BP_ActionShrinkToSmallestCircleDeathZone_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_ActionShrinkToSmallestCircleDeathZone.BP_ActionShrinkToSmallestCircleDeathZone_C.ExecuteUbergraph_BP_ActionShrinkToSmallestCircleDeathZone
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ActionShrinkToSmallestCircleDeathZone_C::ExecuteUbergraph_BP_ActionShrinkToSmallestCircleDeathZone(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionShrinkToSmallestCircleDeathZone_C", "ExecuteUbergraph_BP_ActionShrinkToSmallestCircleDeathZone");

	Params::BP_ActionShrinkToSmallestCircleDeathZone_C_ExecuteUbergraph_BP_ActionShrinkToSmallestCircleDeathZone Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionShrinkToSmallestCircleDeathZone.BP_ActionShrinkToSmallestCircleDeathZone_C.Start Action Validated
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_ActionShrinkToSmallestCircleDeathZone_C::Start_Action_Validated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionShrinkToSmallestCircleDeathZone_C", "Start Action Validated");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
