#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionDefeatTeam

#include "Basic.hpp"

#include "BP_ActionDefeatTeam_classes.hpp"
#include "BP_ActionDefeatTeam_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_ActionDefeatTeam.BP_ActionDefeatTeam_C.ExecuteUbergraph_BP_ActionDefeatTeam
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ActionDefeatTeam_C::ExecuteUbergraph_BP_ActionDefeatTeam(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDefeatTeam_C", "ExecuteUbergraph_BP_ActionDefeatTeam");

	Params::BP_ActionDefeatTeam_C_ExecuteUbergraph_BP_ActionDefeatTeam Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionDefeatTeam.BP_ActionDefeatTeam_C.Start Action Validated
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_ActionDefeatTeam_C::Start_Action_Validated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionDefeatTeam_C", "Start Action Validated");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
