#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionChangeMaxPreGame

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ActionBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ActionChangeMaxPreGame.BP_ActionChangeMaxPreGame_C
// 0x0008 (0x0268 - 0x0260)
class ABP_ActionChangeMaxPreGame_C final : public ABP_ActionBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_ActionChangeMaxPreGame_C;        // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_ActionChangeMaxPreGame(int32 EntryPoint);
	void Start_Action_Validated();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ActionChangeMaxPreGame_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ActionChangeMaxPreGame_C")
	}
	static class ABP_ActionChangeMaxPreGame_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ActionChangeMaxPreGame_C>();
	}
};
DUMPER7_ASSERTS_ABP_ActionChangeMaxPreGame_C;

SDK_NAMESPACE_END
