#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionCommandSails

#include "Basic.hpp"

#include "BP_ActionCommandSails_classes.hpp"
#include "BP_ActionCommandSails_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_ActionCommandSails.BP_ActionCommandSails_C.ExecuteUbergraph_BP_ActionCommandSails
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ActionCommandSails_C::ExecuteUbergraph_BP_ActionCommandSails(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionCommandSails_C", "ExecuteUbergraph_BP_ActionCommandSails");

	Params::BP_ActionCommandSails_C_ExecuteUbergraph_BP_ActionCommandSails Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActionCommandSails.BP_ActionCommandSails_C.Start Action Internal
// (BlueprintCallable, BlueprintEvent)

void ABP_ActionCommandSails_C::Start_Action_Internal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActionCommandSails_C", "Start Action Internal");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
