#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActionMarklocation

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_ActionMarklocation.BP_ActionMarklocation_C.ExecuteUbergraph_BP_ActionMarklocation
// 0x0004 (0x0004 - 0x0000)
struct BP_ActionMarklocation_C_ExecuteUbergraph_BP_ActionMarklocation final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_ActionMarklocation_C_ExecuteUbergraph_BP_ActionMarklocation;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
