#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Brig_MastBaseFront

#include "Basic.hpp"

#include "BP_Brig_MastBaseFront_classes.hpp"
#include "BP_Brig_MastBaseFront_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Brig_MastBaseFront.BP_Brig_MastBaseFront_C.ExecuteUbergraph_BP_Brig_MastBaseFront
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Brig_MastBaseFront_C::ExecuteUbergraph_BP_Brig_MastBaseFront(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Brig_MastBaseFront_C", "ExecuteUbergraph_BP_Brig_MastBaseFront");

	Params::BP_Brig_MastBaseFront_C_ExecuteUbergraph_BP_Brig_MastBaseFront Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Brig_MastBaseFront.BP_Brig_MastBaseFront_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Brig_MastBaseFront_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Brig_MastBaseFront_C", "ReceiveTick");

	Params::BP_Brig_MastBaseFront_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
