#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BoatMeshBase

#include "Basic.hpp"

#include "BP_BoatMeshBase_classes.hpp"
#include "BP_BoatMeshBase_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_BoatMeshBase.BP_BoatMeshBase_C.ExecuteUbergraph_BP_BoatMeshBase
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BoatMeshBase_C::ExecuteUbergraph_BP_BoatMeshBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "ExecuteUbergraph_BP_BoatMeshBase");

	Params::BP_BoatMeshBase_C_ExecuteUbergraph_BP_BoatMeshBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.Initialize
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_BoatMeshBase_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.LaddersLoaded
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::LaddersLoaded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "LaddersLoaded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.MC_FrontalHit
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   ImpactStrength                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BoatMeshBase_C::MC_FrontalHit(float ImpactStrength)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "MC_FrontalHit");

	Params::BP_BoatMeshBase_C_MC_FrontalHit Parms{};

	Parms.ImpactStrength = ImpactStrength;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.RefreshCapstanAndWheel
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::RefreshCapstanAndWheel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "RefreshCapstanAndWheel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.RopeColorRepEvent
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::RopeColorRepEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "RopeColorRepEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.ShipCulling
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::ShipCulling()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "ShipCulling");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABP_BoatMeshBase_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.MC_DestructionEffects
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::MC_DestructionEffects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "MC_DestructionEffects");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.DestroyShip
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::DestroyShip()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "DestroyShip");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.MC_SetStartTransform
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FTransform&                Transform                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)

void ABP_BoatMeshBase_C::MC_SetStartTransform(const struct FTransform& Transform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "MC_SetStartTransform");

	Params::BP_BoatMeshBase_C_MC_SetStartTransform Parms{};

	Parms.Transform = std::move(Transform);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.MC_AnchorStopSplash
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::MC_AnchorStopSplash()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "MC_AnchorStopSplash");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.MC_Rotation
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FRotator&                  Yaw_0                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BoatMeshBase_C::MC_Rotation(const struct FRotator& Yaw_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "MC_Rotation");

	Params::BP_BoatMeshBase_C_MC_Rotation Parms{};

	Parms.Yaw_0 = std::move(Yaw_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.ReplicateRotation
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FRotator&                  Yaw_0                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BoatMeshBase_C::ReplicateRotation(const struct FRotator& Yaw_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "ReplicateRotation");

	Params::BP_BoatMeshBase_C_ReplicateRotation Parms{};

	Parms.Yaw_0 = std::move(Yaw_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.ReplicateLocation
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   BowWaterHeight                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BoatMeshBase_C::ReplicateLocation(const struct FVector& Location, const struct FVector& BowWaterHeight)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "ReplicateLocation");

	Params::BP_BoatMeshBase_C_ReplicateLocation Parms{};

	Parms.Location = std::move(Location);
	Parms.BowWaterHeight = std::move(BowWaterHeight);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.MC_Location
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   XLocation                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   YLocation                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ZLocation                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BoatMeshBase_C::MC_Location(int32 XLocation, int32 YLocation, int32 ZLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "MC_Location");

	Params::BP_BoatMeshBase_C_MC_Location Parms{};

	Parms.XLocation = XLocation;
	Parms.YLocation = YLocation;
	Parms.ZLocation = ZLocation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BoatMeshBase_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "ReceiveTick");

	Params::BP_BoatMeshBase_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.SinkTilt__UpdateFunc
// (BlueprintEvent)

void ABP_BoatMeshBase_C::SinkTilt__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "SinkTilt__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.SinkTilt__FinishedFunc
// (BlueprintEvent)

void ABP_BoatMeshBase_C::SinkTilt__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "SinkTilt__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.Sinking__UpdateFunc
// (BlueprintEvent)

void ABP_BoatMeshBase_C::Sinking__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "Sinking__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.Sinking__FinishedFunc
// (BlueprintEvent)

void ABP_BoatMeshBase_C::Sinking__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "Sinking__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.CollectPointLocations
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FVector>*                 BuoyancyPoints                                         (Parm, OutParm)
// TArray<struct FVector>*                 OriginalLocations                                      (Parm, OutParm)

void ABP_BoatMeshBase_C::CollectPointLocations(TArray<struct FVector>* BuoyancyPoints, TArray<struct FVector>* OriginalLocations)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "CollectPointLocations");

	Params::BP_BoatMeshBase_C_CollectPointLocations Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (BuoyancyPoints != nullptr)
		*BuoyancyPoints = std::move(Parms.BuoyancyPoints);

	if (OriginalLocations != nullptr)
		*OriginalLocations = std::move(Parms.OriginalLocations);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.MovePoints
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Vector                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UStaticMeshComponent*             Point                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BoatMeshBase_C::MovePoints(const struct FVector& Vector, class UStaticMeshComponent* Point)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "MovePoints");

	Params::BP_BoatMeshBase_C_MovePoints Parms{};

	Parms.Vector = std::move(Vector);
	Parms.Point = Point;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.SetPointVisibility
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::SetPointVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "SetPointVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.AddDamage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   DamageAmount                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// E_DamageType                            DamageType                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   RelativeLocation                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    NoSound                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BoatMeshBase_C::AddDamage(int32 DamageAmount, E_DamageType DamageType, const struct FVector& RelativeLocation, bool NoSound)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "AddDamage");

	Params::BP_BoatMeshBase_C_AddDamage Parms{};

	Parms.DamageAmount = DamageAmount;
	Parms.DamageType = DamageType;
	Parms.RelativeLocation = std::move(RelativeLocation);
	Parms.NoSound = NoSound;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.RestoreDamage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   RestoreAmount                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BoatMeshBase_C::RestoreDamage(int32 RestoreAmount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "RestoreDamage");

	Params::BP_BoatMeshBase_C_RestoreDamage Parms{};

	Parms.RestoreAmount = RestoreAmount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_TeamID
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_TeamID()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_TeamID");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.CreateRandomDamage
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Damage_Amount                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<int32>*                          DamageAmounts                                          (Parm, OutParm)
// TArray<struct FVector>*                 DamageLocations                                        (Parm, OutParm)

void ABP_BoatMeshBase_C::CreateRandomDamage(int32 Damage_Amount, TArray<int32>* DamageAmounts, TArray<struct FVector>* DamageLocations)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "CreateRandomDamage");

	Params::BP_BoatMeshBase_C_CreateRandomDamage Parms{};

	Parms.Damage_Amount = Damage_Amount;

	UObject::ProcessEvent(Func, &Parms);

	if (DamageAmounts != nullptr)
		*DamageAmounts = std::move(Parms.DamageAmounts);

	if (DamageLocations != nullptr)
		*DamageLocations = std::move(Parms.DamageLocations);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.ChangeWaterLevel
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Amount                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BoatMeshBase_C::ChangeWaterLevel(float Amount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "ChangeWaterLevel");

	Params::BP_BoatMeshBase_C_ChangeWaterLevel Parms{};

	Parms.Amount = Amount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.CheckIfPointIsBelowWaterLevel
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   PointLocation                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// E_WaterHull                             WaterDamage                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   IsBelowWaterLevel                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BoatMeshBase_C::CheckIfPointIsBelowWaterLevel(const struct FVector& PointLocation, E_WaterHull WaterDamage, bool* IsBelowWaterLevel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "CheckIfPointIsBelowWaterLevel");

	Params::BP_BoatMeshBase_C_CheckIfPointIsBelowWaterLevel Parms{};

	Parms.PointLocation = std::move(PointLocation);
	Parms.WaterDamage = WaterDamage;

	UObject::ProcessEvent(Func, &Parms);

	if (IsBelowWaterLevel != nullptr)
		*IsBelowWaterLevel = Parms.IsBelowWaterLevel;
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_Going forward
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_Going_forward()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_Going forward");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_Destroyed
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_Destroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_Destroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_HullColor
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_HullColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_HullColor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_SailColor
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_SailColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_SailColor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.LoadSailColor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   SuccesfullyLoaded                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BoatMeshBase_C::LoadSailColor(bool* SuccesfullyLoaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "LoadSailColor");

	Params::BP_BoatMeshBase_C_LoadSailColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SuccesfullyLoaded != nullptr)
		*SuccesfullyLoaded = Parms.SuccesfullyLoaded;
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_SailEmblem
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_SailEmblem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_SailEmblem");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.LoadSailEmblem
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   SuccesfullyLoaded                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BoatMeshBase_C::LoadSailEmblem(bool* SuccesfullyLoaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "LoadSailEmblem");

	Params::BP_BoatMeshBase_C_LoadSailEmblem Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SuccesfullyLoaded != nullptr)
		*SuccesfullyLoaded = Parms.SuccesfullyLoaded;
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_BowFigureHead
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_BowFigureHead()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_BowFigureHead");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_FlagColor
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_FlagColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_FlagColor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.LoadFlagColor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   SuccesfullyLoaded                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BoatMeshBase_C::LoadFlagColor(bool* SuccesfullyLoaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "LoadFlagColor");

	Params::BP_BoatMeshBase_C_LoadFlagColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SuccesfullyLoaded != nullptr)
		*SuccesfullyLoaded = Parms.SuccesfullyLoaded;
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_RopeColor
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_RopeColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_RopeColor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.LoadRopeColor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   SuccesfullyLoaded                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BoatMeshBase_C::LoadRopeColor(bool* SuccesfullyLoaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "LoadRopeColor");

	Params::BP_BoatMeshBase_C_LoadRopeColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SuccesfullyLoaded != nullptr)
		*SuccesfullyLoaded = Parms.SuccesfullyLoaded;
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_FlagEmblem
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_FlagEmblem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_FlagEmblem");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.LoadFlagEmblem
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   FlagEmblemIndex                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   SpecialFlagIndex                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   SuccesfullyLoaded                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BoatMeshBase_C::LoadFlagEmblem(int32 FlagEmblemIndex, int32 SpecialFlagIndex, bool* SuccesfullyLoaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "LoadFlagEmblem");

	Params::BP_BoatMeshBase_C_LoadFlagEmblem Parms{};

	Parms.FlagEmblemIndex = FlagEmblemIndex;
	Parms.SpecialFlagIndex = SpecialFlagIndex;

	UObject::ProcessEvent(Func, &Parms);

	if (SuccesfullyLoaded != nullptr)
		*SuccesfullyLoaded = Parms.SuccesfullyLoaded;
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.UpgradeSteeringWheel
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Upgrade_Amount                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Upgraded                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BoatMeshBase_C::UpgradeSteeringWheel(int32 Upgrade_Amount, bool* Upgraded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "UpgradeSteeringWheel");

	Params::BP_BoatMeshBase_C_UpgradeSteeringWheel Parms{};

	Parms.Upgrade_Amount = Upgrade_Amount;

	UObject::ProcessEvent(Func, &Parms);

	if (Upgraded != nullptr)
		*Upgraded = Parms.Upgraded;
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_SteeringWheelLevel
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_SteeringWheelLevel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_SteeringWheelLevel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_LampColor
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_LampColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_LampColor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_MarkerRef
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_MarkerRef()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_MarkerRef");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.SpawnDestroyedContainer
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::SpawnDestroyedContainer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "SpawnDestroyedContainer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_SailEmblemBottom
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_SailEmblemBottom()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_SailEmblemBottom");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_SailColorBottom
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_SailColorBottom()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_SailColorBottom");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_ShipPaint
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_ShipPaint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_ShipPaint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.GetYaw
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   Yaw_0                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  YawResult                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BoatMeshBase_C::GetYaw(float Yaw_0, float* YawResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "GetYaw");

	Params::BP_BoatMeshBase_C_GetYaw Parms{};

	Parms.Yaw_0 = Yaw_0;

	UObject::ProcessEvent(Func, &Parms);

	if (YawResult != nullptr)
		*YawResult = Parms.YawResult;
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.SetShipName
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      ShipName                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void ABP_BoatMeshBase_C::SetShipName(const class FText& ShipName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "SetShipName");

	Params::BP_BoatMeshBase_C_SetShipName Parms{};

	Parms.ShipName = std::move(ShipName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.SetCosmetics
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FST_ShipCustomisations_renamed&Customization                                          (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABP_BoatMeshBase_C::SetCosmetics(const struct FST_ShipCustomisations_renamed& Customization)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "SetCosmetics");

	Params::BP_BoatMeshBase_C_SetCosmetics Parms{};

	Parms.Customization = std::move(Customization);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_ShipPaintColor
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_ShipPaintColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_ShipPaintColor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_BowFigureColor
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_BowFigureColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_BowFigureColor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.HideComponents
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::HideComponents()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "HideComponents");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.UnhideComponents
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::UnhideComponents()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "UnhideComponents");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.CheckIfValidComponentForHiding
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           ChildActorRef                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Valid                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BoatMeshBase_C::CheckIfValidComponentForHiding(class AActor* ChildActorRef, bool* Valid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "CheckIfValidComponentForHiding");

	Params::BP_BoatMeshBase_C_CheckIfValidComponentForHiding Parms{};

	Parms.ChildActorRef = ChildActorRef;

	UObject::ProcessEvent(Func, &Parms);

	if (Valid != nullptr)
		*Valid = Parms.Valid;
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_BowFigureColorSet1
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_BowFigureColorSet1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_BowFigureColorSet1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_BowFigureColorSet2
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_BowFigureColorSet2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_BowFigureColorSet2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_BowFigureColorSet3
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_BowFigureColorSet3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_BowFigureColorSet3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_ShipPaintDamageAmount
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_ShipPaintDamageAmount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_ShipPaintDamageAmount");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.AddOrChangeInstalledUpgrades
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_Items                                 NewUpgrade                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BoatMeshBase_C::AddOrChangeInstalledUpgrades(E_Items NewUpgrade)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "AddOrChangeInstalledUpgrades");

	Params::BP_BoatMeshBase_C_AddOrChangeInstalledUpgrades Parms{};

	Parms.NewUpgrade = NewUpgrade;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.CheckIfShipIsVisible
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   PlayerLocation                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   EntireShipBlocked                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BoatMeshBase_C::CheckIfShipIsVisible(const struct FVector& PlayerLocation, bool* EntireShipBlocked)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "CheckIfShipIsVisible");

	Params::BP_BoatMeshBase_C_CheckIfShipIsVisible Parms{};

	Parms.PlayerLocation = std::move(PlayerLocation);

	UObject::ProcessEvent(Func, &Parms);

	if (EntireShipBlocked != nullptr)
		*EntireShipBlocked = Parms.EntireShipBlocked;
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.GetTiltMultiplier
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    AnchorStop                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float*                                  Multiplier                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BoatMeshBase_C::GetTiltMultiplier(bool AnchorStop, float* Multiplier)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "GetTiltMultiplier");

	Params::BP_BoatMeshBase_C_GetTiltMultiplier Parms{};

	Parms.AnchorStop = AnchorStop;

	UObject::ProcessEvent(Func, &Parms);

	if (Multiplier != nullptr)
		*Multiplier = Parms.Multiplier;
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_SpecialFlag
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_SpecialFlag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_SpecialFlag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_FlagsSwapped
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_FlagsSwapped()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_FlagsSwapped");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_FlagSetup
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_FlagSetup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_FlagSetup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_FleetID
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_FleetID()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_FleetID");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_SailTearAmount
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_SailTearAmount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_SailTearAmount");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_SailDirtAmount
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_SailDirtAmount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_SailDirtAmount");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.OnRep_SailPaintWearAmount
// (BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::OnRep_SailPaintWearAmount()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "OnRep_SailPaintWearAmount");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.GetBowFigureTransform
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FName                             RowName                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FTransform*                      Transform                                              (Parm, OutParm, IsPlainOldData, NoDestructor)

void ABP_BoatMeshBase_C::GetBowFigureTransform(class FName RowName, struct FTransform* Transform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "GetBowFigureTransform");

	Params::BP_BoatMeshBase_C_GetBowFigureTransform Parms{};

	Parms.RowName = RowName;

	UObject::ProcessEvent(Func, &Parms);

	if (Transform != nullptr)
		*Transform = std::move(Parms.Transform);
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.GetFirstControllerInTeam
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeamID                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_Controller_C**                ControllerRef                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BoatMeshBase_C::GetFirstControllerInTeam(int32 TeamID, class ABP_Controller_C** ControllerRef)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "GetFirstControllerInTeam");

	Params::BP_BoatMeshBase_C_GetFirstControllerInTeam Parms{};

	Parms.TeamID = TeamID;

	UObject::ProcessEvent(Func, &Parms);

	if (ControllerRef != nullptr)
		*ControllerRef = Parms.ControllerRef;
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.IsMyShip
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UTeam_Crew_Ship_Member_State_C*   Other_ship_crew_member_state                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   MyShip                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BoatMeshBase_C::IsMyShip(class UTeam_Crew_Ship_Member_State_C* Other_ship_crew_member_state, bool* MyShip)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "IsMyShip");

	Params::BP_BoatMeshBase_C_IsMyShip Parms{};

	Parms.Other_ship_crew_member_state = Other_ship_crew_member_state;

	UObject::ProcessEvent(Func, &Parms);

	if (MyShip != nullptr)
		*MyShip = Parms.MyShip;
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.IsMyTeamShip
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UTeam_Crew_Ship_Member_State_C*   Other_Crew_member_state                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   MyShip                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_BoatMeshBase_C::IsMyTeamShip(class UTeam_Crew_Ship_Member_State_C* Other_Crew_member_state, bool* MyShip)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "IsMyTeamShip");

	Params::BP_BoatMeshBase_C_IsMyTeamShip Parms{};

	Parms.Other_Crew_member_state = Other_Crew_member_state;

	UObject::ProcessEvent(Func, &Parms);

	if (MyShip != nullptr)
		*MyShip = Parms.MyShip;
}


// Function BP_BoatMeshBase.BP_BoatMeshBase_C.Update Team Crew ID on Others
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_BoatMeshBase_C::Update_Team_Crew_ID_on_Others()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BoatMeshBase_C", "Update Team Crew ID on Others");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
