#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BoatPhysicsBase_BombVessel

#include "Basic.hpp"

#include "BP_BoatPhysicsBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BoatPhysicsBase_BombVessel.BP_BoatPhysicsBase_BombVessel_C
// 0x0000 (0x0340 - 0x0340)
class ABP_BoatPhysicsBase_BombVessel_C final : public ABP_BoatPhysicsBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BoatPhysicsBase_BombVessel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BoatPhysicsBase_BombVessel_C")
	}
	static class ABP_BoatPhysicsBase_BombVessel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BoatPhysicsBase_BombVessel_C>();
	}
};
DUMPER7_ASSERTS_ABP_BoatPhysicsBase_BombVessel_C;

SDK_NAMESPACE_END
