#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ConquestFlag

#include "Basic.hpp"

#include "BP_ConquestFlag_classes.hpp"
#include "BP_ConquestFlag_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_ConquestFlag.BP_ConquestFlag_C.ExecuteUbergraph_BP_ConquestFlag
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ConquestFlag_C::ExecuteUbergraph_BP_ConquestFlag(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestFlag_C", "ExecuteUbergraph_BP_ConquestFlag");

	Params::BP_ConquestFlag_C_ExecuteUbergraph_BP_ConquestFlag Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ConquestFlag.BP_ConquestFlag_C.ResetFlag
// (BlueprintCallable, BlueprintEvent)

void ABP_ConquestFlag_C::ResetFlag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestFlag_C", "ResetFlag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestFlag.BP_ConquestFlag_C.DisableFlag
// (BlueprintCallable, BlueprintEvent)

void ABP_ConquestFlag_C::DisableFlag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestFlag_C", "DisableFlag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestFlag.BP_ConquestFlag_C.EnableFlag
// (BlueprintCallable, BlueprintEvent)

void ABP_ConquestFlag_C::EnableFlag()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestFlag_C", "EnableFlag");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestFlag.BP_ConquestFlag_C.SetConquestDecal
// (BlueprintCallable, BlueprintEvent)

void ABP_ConquestFlag_C::SetConquestDecal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestFlag_C", "SetConquestDecal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestFlag.BP_ConquestFlag_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ConquestFlag_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestFlag_C", "ReceiveTick");

	Params::BP_ConquestFlag_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ConquestFlag.BP_ConquestFlag_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_ConquestFlag_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestFlag_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestFlag.BP_ConquestFlag_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_ConquestFlag_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestFlag_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestFlag.BP_ConquestFlag_C.OnRep_ControllingTeam
// (HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_ConquestFlag_C::OnRep_ControllingTeam()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestFlag_C", "OnRep_ControllingTeam");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestFlag.BP_ConquestFlag_C.DecideCaptureProgress
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   StaleMate                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32*                                  BlueTeamPlayers                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  RedTeamPlayers                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ConquestFlag_C::DecideCaptureProgress(bool* StaleMate, int32* BlueTeamPlayers, int32* RedTeamPlayers)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestFlag_C", "DecideCaptureProgress");

	Params::BP_ConquestFlag_C_DecideCaptureProgress Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (StaleMate != nullptr)
		*StaleMate = Parms.StaleMate;

	if (BlueTeamPlayers != nullptr)
		*BlueTeamPlayers = Parms.BlueTeamPlayers;

	if (RedTeamPlayers != nullptr)
		*RedTeamPlayers = Parms.RedTeamPlayers;
}


// Function BP_ConquestFlag.BP_ConquestFlag_C.GetCaptureDirection
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float*                                  DirectionMultiuplier                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ConquestFlag_C::GetCaptureDirection(float* DirectionMultiuplier)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestFlag_C", "GetCaptureDirection");

	Params::BP_ConquestFlag_C_GetCaptureDirection Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (DirectionMultiuplier != nullptr)
		*DirectionMultiuplier = Parms.DirectionMultiuplier;
}


// Function BP_ConquestFlag.BP_ConquestFlag_C.SetWidgetFollowPosition
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_ConquestFlag_C::SetWidgetFollowPosition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestFlag_C", "SetWidgetFollowPosition");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ConquestFlag.BP_ConquestFlag_C.IsPoleInView
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   IsInView                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_ConquestFlag_C::IsPoleInView(bool* IsInView)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestFlag_C", "IsPoleInView");

	Params::BP_ConquestFlag_C_IsPoleInView Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsInView != nullptr)
		*IsInView = Parms.IsInView;
}


// Function BP_ConquestFlag.BP_ConquestFlag_C.OnRep_Enabled
// (BlueprintCallable, BlueprintEvent)

void ABP_ConquestFlag_C::OnRep_Enabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ConquestFlag_C", "OnRep_Enabled");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
