#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ContainerShip

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ContainerBase_classes.hpp"
#include "E_Items_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ContainerShip.BP_ContainerShip_C
// 0x0020 (0x0408 - 0x03E8)
class ABP_ContainerShip_C final : public ABP_ContainerBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_ContainerShip_C;                 // 0x03E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABP_BoatMeshBase_C*                     ShipRef;                                           // 0x03F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              AllDeposited;                                      // 0x03F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ExecuteUbergraph_BP_ContainerShip(int32 EntryPoint);
	void RefreshQuickAccessPoints();
	void ReceiveBeginPlay();
	void SpawnDuplicateShipDeathContainer(TArray<E_Items>& InstalledUpgrades, const struct FVector& SpawnLocation);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ContainerShip_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ContainerShip_C")
	}
	static class ABP_ContainerShip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ContainerShip_C>();
	}
};
DUMPER7_ASSERTS_ABP_ContainerShip_C;

SDK_NAMESPACE_END
