#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_COM_Controller

#include "Basic.hpp"

#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_COM_Controller.BP_COM_Controller_C.COM_Get Unique Net ID
// 0x0028 (0x0028 - 0x0000)
struct BP_COM_Controller_C_COM_Get_Unique_Net_ID final
{
public:
	struct FUniqueNetIdRepl                       Unique_Net_Id;                                     // 0x0000(0x0028)(Parm, OutParm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_COM_Controller_C_COM_Get_Unique_Net_ID;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
