#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CannonBallChest

#include "Basic.hpp"

#include "BP_CannonBallChest_classes.hpp"
#include "BP_CannonBallChest_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_CannonBallChest.BP_CannonBallChest_C.ExecuteUbergraph_BP_CannonBallChest
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CannonBallChest_C::ExecuteUbergraph_BP_CannonBallChest(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CannonBallChest_C", "ExecuteUbergraph_BP_CannonBallChest");

	Params::BP_CannonBallChest_C_ExecuteUbergraph_BP_CannonBallChest Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CannonBallChest.BP_CannonBallChest_C.S_Activate
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_CannonBallChest_C::S_Activate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CannonBallChest_C", "S_Activate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CannonBallChest.BP_CannonBallChest_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CannonBallChest_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CannonBallChest_C", "ReceiveTick");

	Params::BP_CannonBallChest_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CannonBallChest.BP_CannonBallChest_C.Activate
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Character_C*                  LocalCharacterRef                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CannonBallChest_C::Activate(class ABP_Character_C* LocalCharacterRef)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CannonBallChest_C", "Activate");

	Params::BP_CannonBallChest_C_Activate Parms{};

	Parms.LocalCharacterRef = LocalCharacterRef;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CannonBallChest.BP_CannonBallChest_C.CloseChest
// (BlueprintCallable, BlueprintEvent)

void ABP_CannonBallChest_C::CloseChest()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CannonBallChest_C", "CloseChest");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CannonBallChest.BP_CannonBallChest_C.ShowReceivedIndicator
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   CannonballAmount                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   AntiSailAmount                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CannonBallChest_C::ShowReceivedIndicator(int32 CannonballAmount, int32 AntiSailAmount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CannonBallChest_C", "ShowReceivedIndicator");

	Params::BP_CannonBallChest_C_ShowReceivedIndicator Parms{};

	Parms.CannonballAmount = CannonballAmount;
	Parms.AntiSailAmount = AntiSailAmount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CannonBallChest.BP_CannonBallChest_C.GiveCannonballs
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_CannonBallChest_C::GiveCannonballs()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CannonBallChest_C", "GiveCannonballs");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
