#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CapstanSloop

#include "Basic.hpp"

#include "BP_CapstanSloop_classes.hpp"
#include "BP_CapstanSloop_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_CapstanSloop.BP_CapstanSloop_C.ExecuteUbergraph_BP_CapstanSloop
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CapstanSloop_C::ExecuteUbergraph_BP_CapstanSloop(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CapstanSloop_C", "ExecuteUbergraph_BP_CapstanSloop");

	Params::BP_CapstanSloop_C_ExecuteUbergraph_BP_CapstanSloop Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CapstanSloop.BP_CapstanSloop_C.AnchorRaised
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_CapstanSloop_C::AnchorRaised()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CapstanSloop_C", "AnchorRaised");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CapstanSloop.BP_CapstanSloop_C.MC_UpgradeCapstan
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_CapstanSloop_C::MC_UpgradeCapstan()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CapstanSloop_C", "MC_UpgradeCapstan");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CapstanSloop.BP_CapstanSloop_C.ResetCapstan
// (BlueprintCallable, BlueprintEvent)

void ABP_CapstanSloop_C::ResetCapstan()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CapstanSloop_C", "ResetCapstan");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CapstanSloop.BP_CapstanSloop_C.MC_SetBeingTurned
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    BeingTurned                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_CapstanSloop_C::MC_SetBeingTurned(bool BeingTurned)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CapstanSloop_C", "MC_SetBeingTurned");

	Params::BP_CapstanSloop_C_MC_SetBeingTurned Parms{};

	Parms.BeingTurned = BeingTurned;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CapstanSloop.BP_CapstanSloop_C.MC_SetRotation
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Rotation_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CapstanSloop_C::MC_SetRotation(float Rotation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CapstanSloop_C", "MC_SetRotation");

	Params::BP_CapstanSloop_C_MC_SetRotation Parms{};

	Parms.Rotation_0 = Rotation_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CapstanSloop.BP_CapstanSloop_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CapstanSloop_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CapstanSloop_C", "ReceiveTick");

	Params::BP_CapstanSloop_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CapstanSloop.BP_CapstanSloop_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CapstanSloop_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CapstanSloop_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CapstanSloop.BP_CapstanSloop_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_CapstanSloop_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CapstanSloop_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CapstanSloop.BP_CapstanSloop_C.SetCapstanControllers
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_CapstanSloop_C::SetCapstanControllers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CapstanSloop_C", "SetCapstanControllers");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CapstanSloop.BP_CapstanSloop_C.OnRep_Active
// (BlueprintCallable, BlueprintEvent)

void ABP_CapstanSloop_C::OnRep_Active()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CapstanSloop_C", "OnRep_Active");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CapstanSloop.BP_CapstanSloop_C.OnRep_Level
// (BlueprintCallable, BlueprintEvent)

void ABP_CapstanSloop_C::OnRep_Level()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CapstanSloop_C", "OnRep_Level");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CapstanSloop.BP_CapstanSloop_C.SetCapstanLevelAppearance
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_CapstanSloop_C::SetCapstanLevelAppearance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CapstanSloop_C", "SetCapstanLevelAppearance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CapstanSloop.BP_CapstanSloop_C.UpgradeCapstan
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_CapstanSloop_C::UpgradeCapstan()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CapstanSloop_C", "UpgradeCapstan");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CapstanSloop.BP_CapstanSloop_C.OnRep_CapstanControllers
// (BlueprintCallable, BlueprintEvent)

void ABP_CapstanSloop_C::OnRep_CapstanControllers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CapstanSloop_C", "OnRep_CapstanControllers");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
