#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Elevator

#include "Basic.hpp"

#include "BP_Elevator_classes.hpp"
#include "BP_Elevator_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Elevator.BP_Elevator_C.ExecuteUbergraph_BP_Elevator
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Elevator_C::ExecuteUbergraph_BP_Elevator(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Elevator_C", "ExecuteUbergraph_BP_Elevator");

	Params::BP_Elevator_C_ExecuteUbergraph_BP_Elevator Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Elevator.BP_Elevator_C.ActivateElevator
// (BlueprintCallable, BlueprintEvent)

void ABP_Elevator_C::ActivateElevator()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Elevator_C", "ActivateElevator");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Elevator.BP_Elevator_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Elevator_C::ReceiveTick(float DeltaSeconds_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Elevator_C", "ReceiveTick");

	Params::BP_Elevator_C_ReceiveTick Parms{};

	Parms.DeltaSeconds_0 = DeltaSeconds_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Elevator.BP_Elevator_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Elevator_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Elevator_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Elevator.BP_Elevator_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Elevator_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Elevator_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Elevator.BP_Elevator_C.OnRep_Rising
// (BlueprintCallable, BlueprintEvent)

void ABP_Elevator_C::OnRep_Rising()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Elevator_C", "OnRep_Rising");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Elevator.BP_Elevator_C.OnRep_PlaySound
// (BlueprintCallable, BlueprintEvent)

void ABP_Elevator_C::OnRep_PlaySound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Elevator_C", "OnRep_PlaySound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Elevator.BP_Elevator_C.OnRep_Descending
// (BlueprintCallable, BlueprintEvent)

void ABP_Elevator_C::OnRep_Descending()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Elevator_C", "OnRep_Descending");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Elevator.BP_Elevator_C.ToggleTick
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Elevator_C::ToggleTick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Elevator_C", "ToggleTick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Elevator.BP_Elevator_C.OnRep_IsAtTop
// (BlueprintCallable, BlueprintEvent)

void ABP_Elevator_C::OnRep_IsAtTop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Elevator_C", "OnRep_IsAtTop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Elevator.BP_Elevator_C.OnRep_IsAtBottom
// (BlueprintCallable, BlueprintEvent)

void ABP_Elevator_C::OnRep_IsAtBottom()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Elevator_C", "OnRep_IsAtBottom");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
