#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ElevatorActivator

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_InteractableBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ElevatorActivator.BP_ElevatorActivator_C
// 0x0020 (0x0340 - 0x0320)
class ABP_ElevatorActivator_C final : public ABP_InteractableBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_ElevatorActivator_C;             // 0x0320(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Cube;                                              // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ABP_Elevator_C*                         ElevatorRef;                                       // 0x0330(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         HandleRotation;                                    // 0x0338(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ElevatorActivator(int32 EntryPoint);
	void HandlePosition(bool Left);
	void S_Activate();
	void ReceiveTick(float DeltaSeconds);
	void OnRep_HandleUsed();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ElevatorActivator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ElevatorActivator_C")
	}
	static class ABP_ElevatorActivator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ElevatorActivator_C>();
	}
};
DUMPER7_ASSERTS_ABP_ElevatorActivator_C;

SDK_NAMESPACE_END
