#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EndGameRocksNew

#include "Basic.hpp"

#include "BP_EndGameRocksNew_classes.hpp"
#include "BP_EndGameRocksNew_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_EndGameRocksNew.BP_EndGameRocksNew_C.ExecuteUbergraph_BP_EndGameRocksNew
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EndGameRocksNew_C::ExecuteUbergraph_BP_EndGameRocksNew(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EndGameRocksNew_C", "ExecuteUbergraph_BP_EndGameRocksNew");

	Params::BP_EndGameRocksNew_C_ExecuteUbergraph_BP_EndGameRocksNew Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EndGameRocksNew.BP_EndGameRocksNew_C.ReEnableCollisions
// (BlueprintCallable, BlueprintEvent)

void ABP_EndGameRocksNew_C::ReEnableCollisions()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EndGameRocksNew_C", "ReEnableCollisions");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EndGameRocksNew.BP_EndGameRocksNew_C.RiseRock
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   RiseLocation                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EndGameRocksNew_C::RiseRock(const struct FVector& RiseLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EndGameRocksNew_C", "RiseRock");

	Params::BP_EndGameRocksNew_C_RiseRock Parms{};

	Parms.RiseLocation = std::move(RiseLocation);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EndGameRocksNew.BP_EndGameRocksNew_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EndGameRocksNew_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EndGameRocksNew_C", "ReceiveTick");

	Params::BP_EndGameRocksNew_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EndGameRocksNew.BP_EndGameRocksNew_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_EndGameRocksNew_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EndGameRocksNew_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EndGameRocksNew.BP_EndGameRocksNew_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_EndGameRocksNew_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EndGameRocksNew_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EndGameRocksNew.BP_EndGameRocksNew_C.GetRandomPointInCircle
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector*                         Location                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EndGameRocksNew_C::GetRandomPointInCircle(struct FVector* Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EndGameRocksNew_C", "GetRandomPointInCircle");

	Params::BP_EndGameRocksNew_C_GetRandomPointInCircle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Location != nullptr)
		*Location = std::move(Parms.Location);
}


// Function BP_EndGameRocksNew.BP_EndGameRocksNew_C.CheckIfRockCanSpawn
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   CanSpawn                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_EndGameRocksNew_C::CheckIfRockCanSpawn(const struct FVector& Location, bool* CanSpawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EndGameRocksNew_C", "CheckIfRockCanSpawn");

	Params::BP_EndGameRocksNew_C_CheckIfRockCanSpawn Parms{};

	Parms.Location = std::move(Location);

	UObject::ProcessEvent(Func, &Parms);

	if (CanSpawn != nullptr)
		*CanSpawn = Parms.CanSpawn;
}


// Function BP_EndGameRocksNew.BP_EndGameRocksNew_C.OnRep_ActualRockLocation
// (HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_EndGameRocksNew_C::OnRep_ActualRockLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EndGameRocksNew_C", "OnRep_ActualRockLocation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EndGameRocksNew.BP_EndGameRocksNew_C.OnRep_MaxRock1Height
// (BlueprintCallable, BlueprintEvent)

void ABP_EndGameRocksNew_C::OnRep_MaxRock1Height()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EndGameRocksNew_C", "OnRep_MaxRock1Height");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EndGameRocksNew.BP_EndGameRocksNew_C.OnRep_MaxRock2Height
// (BlueprintCallable, BlueprintEvent)

void ABP_EndGameRocksNew_C::OnRep_MaxRock2Height()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EndGameRocksNew_C", "OnRep_MaxRock2Height");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EndGameRocksNew.BP_EndGameRocksNew_C.OnRep_MaxRock3Height
// (BlueprintCallable, BlueprintEvent)

void ABP_EndGameRocksNew_C::OnRep_MaxRock3Height()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EndGameRocksNew_C", "OnRep_MaxRock3Height");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
