#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EmoteWave

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ActionBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_EmoteWave.BP_EmoteWave_C
// 0x0008 (0x0268 - 0x0260)
class ABP_EmoteWave_C final : public ABP_ActionBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_EmoteWave_C;                     // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_EmoteWave(int32 EntryPoint);
	void Start_Action_Internal();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_EmoteWave_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_EmoteWave_C")
	}
	static class ABP_EmoteWave_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EmoteWave_C>();
	}
};
DUMPER7_ASSERTS_ABP_EmoteWave_C;

SDK_NAMESPACE_END
