#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Gamemode_Base

#include "Basic.hpp"

#include "Alpha_GameMode_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Gamemode_Base.BP_Gamemode_Base_C
// 0x0000 (0x04B0 - 0x04B0)
class ABP_Gamemode_Base_C : public AAlpha_GameMode_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Gamemode_Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Gamemode_Base_C")
	}
	static class ABP_Gamemode_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Gamemode_Base_C>();
	}
};
DUMPER7_ASSERTS_ABP_Gamemode_Base_C;

SDK_NAMESPACE_END
