#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GalleonDamagePoints

#include "Basic.hpp"

#include "BP_GalleonDamagePoints_classes.hpp"
#include "BP_GalleonDamagePoints_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_GalleonDamagePoints.BP_GalleonDamagePoints_C.ExecuteUbergraph_BP_GalleonDamagePoints
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GalleonDamagePoints_C::ExecuteUbergraph_BP_GalleonDamagePoints(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GalleonDamagePoints_C", "ExecuteUbergraph_BP_GalleonDamagePoints");

	Params::BP_GalleonDamagePoints_C_ExecuteUbergraph_BP_GalleonDamagePoints Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GalleonDamagePoints.BP_GalleonDamagePoints_C.PrepPoints
// (BlueprintCallable, BlueprintEvent)

void ABP_GalleonDamagePoints_C::PrepPoints()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GalleonDamagePoints_C", "PrepPoints");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GalleonDamagePoints.BP_GalleonDamagePoints_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_GalleonDamagePoints_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GalleonDamagePoints_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GalleonDamagePoints.BP_GalleonDamagePoints_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_GalleonDamagePoints_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GalleonDamagePoints_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GalleonDamagePoints.BP_GalleonDamagePoints_C.DestroyUnwantedDamagePoint
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UChildActorComponent*             DamagePointRef                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GalleonDamagePoints_C::DestroyUnwantedDamagePoint(class UChildActorComponent* DamagePointRef)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GalleonDamagePoints_C", "DestroyUnwantedDamagePoint");

	Params::BP_GalleonDamagePoints_C_DestroyUnwantedDamagePoint Parms{};

	Parms.DamagePointRef = DamagePointRef;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
