#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameMode_ConquestMode

#include "Basic.hpp"

#include "BP_GameMode_ConquestMode_classes.hpp"
#include "BP_GameMode_ConquestMode_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.ExecuteUbergraph_BP_GameMode_ConquestMode
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GameMode_ConquestMode_C::ExecuteUbergraph_BP_GameMode_ConquestMode(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "ExecuteUbergraph_BP_GameMode_ConquestMode");

	Params::BP_GameMode_ConquestMode_C_ExecuteUbergraph_BP_GameMode_ConquestMode Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.EndConquestMatchEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   WinningFleet                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GameMode_ConquestMode_C::EndConquestMatchEvent(int32 WinningFleet)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "EndConquestMatchEvent");

	Params::BP_GameMode_ConquestMode_C_EndConquestMatchEvent Parms{};

	Parms.WinningFleet = WinningFleet;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.TeamCreatedEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeamID                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GameMode_ConquestMode_C::TeamCreatedEvent(int32 TeamID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "TeamCreatedEvent");

	Params::BP_GameMode_ConquestMode_C_TeamCreatedEvent Parms{};

	Parms.TeamID = TeamID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.StartGameEvent(TickingEvent)
// (BlueprintCallable, BlueprintEvent)

void ABP_GameMode_ConquestMode_C::StartGameEvent_TickingEvent_()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "StartGameEvent(TickingEvent)");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.K2_OnLogout
// (Event, Public, BlueprintEvent)
// Parameters:
// class AController*                      ExitingController                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GameMode_ConquestMode_C::K2_OnLogout(class AController* ExitingController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "K2_OnLogout");

	Params::BP_GameMode_ConquestMode_C_K2_OnLogout Parms{};

	Parms.ExitingController = ExitingController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GameMode_ConquestMode_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "ReceiveTick");

	Params::BP_GameMode_ConquestMode_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.K2_PostLogin
// (Event, Public, BlueprintEvent)
// Parameters:
// class APlayerController*                NewPlayer                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GameMode_ConquestMode_C::K2_PostLogin(class APlayerController* NewPlayer)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "K2_PostLogin");

	Params::BP_GameMode_ConquestMode_C_K2_PostLogin Parms{};

	Parms.NewPlayer = NewPlayer;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_GameMode_ConquestMode_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.StartConquestMatch
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_GameMode_ConquestMode_C::StartConquestMatch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "StartConquestMatch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.GetRandomFleetSpawnPoint
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Fleet                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class ABP_ConquestBoatSpawn_C*>& RemainingSpawnPoints                                   (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_GameMode_ConquestMode_C::GetRandomFleetSpawnPoint(int32 Fleet, TArray<class ABP_ConquestBoatSpawn_C*>& RemainingSpawnPoints)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "GetRandomFleetSpawnPoint");

	Params::BP_GameMode_ConquestMode_C_GetRandomFleetSpawnPoint Parms{};

	Parms.Fleet = Fleet;
	Parms.RemainingSpawnPoints = std::move(RemainingSpawnPoints);

	UObject::ProcessEvent(Func, &Parms);

	RemainingSpawnPoints = std::move(Parms.RemainingSpawnPoints);
}


// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.SortTeamInFleet
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TeamID                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GameMode_ConquestMode_C::SortTeamInFleet(int32 TeamID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "SortTeamInFleet");

	Params::BP_GameMode_ConquestMode_C_SortTeamInFleet Parms{};

	Parms.TeamID = TeamID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.EndConquestMatch
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   WinningFleet                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GameMode_ConquestMode_C::EndConquestMatch(int32 WinningFleet)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "EndConquestMatch");

	Params::BP_GameMode_ConquestMode_C_EndConquestMatch Parms{};

	Parms.WinningFleet = WinningFleet;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.GetRandomFleetSpawnPointMidMatch
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Fleet                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_ConquestBoatSpawn_C**         SpawnPoint                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_GameMode_ConquestMode_C::GetRandomFleetSpawnPointMidMatch(int32 Fleet, class ABP_ConquestBoatSpawn_C** SpawnPoint, bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "GetRandomFleetSpawnPointMidMatch");

	Params::BP_GameMode_ConquestMode_C_GetRandomFleetSpawnPointMidMatch Parms{};

	Parms.Fleet = Fleet;

	UObject::ProcessEvent(Func, &Parms);

	if (SpawnPoint != nullptr)
		*SpawnPoint = Parms.SpawnPoint;

	if (Success != nullptr)
		*Success = Parms.Success;
}


// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.AddShipToSpawnQueue
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   FleetID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   TeamID                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UClass*                           ShipClass_0                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GameMode_ConquestMode_C::AddShipToSpawnQueue(int32 FleetID, int32 TeamID, class UClass* ShipClass_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "AddShipToSpawnQueue");

	Params::BP_GameMode_ConquestMode_C_AddShipToSpawnQueue Parms{};

	Parms.FleetID = FleetID;
	Parms.TeamID = TeamID;
	Parms.ShipClass_0 = ShipClass_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.AddInitialResourcesToShip
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_BoatMeshBase_C*               ShipRef                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GameMode_ConquestMode_C::AddInitialResourcesToShip(class ABP_BoatMeshBase_C* ShipRef)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "AddInitialResourcesToShip");

	Params::BP_GameMode_ConquestMode_C_AddInitialResourcesToShip Parms{};

	Parms.ShipRef = ShipRef;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.FullyUpgradeShip
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_BoatMeshBase_C*               ShipRef                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GameMode_ConquestMode_C::FullyUpgradeShip(class ABP_BoatMeshBase_C* ShipRef)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "FullyUpgradeShip");

	Params::BP_GameMode_ConquestMode_C_FullyUpgradeShip Parms{};

	Parms.ShipRef = ShipRef;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.RandomizeFlags
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_ConquestFlag_C**              NewConquestFlagRef                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GameMode_ConquestMode_C::RandomizeFlags(class ABP_ConquestFlag_C** NewConquestFlagRef)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "RandomizeFlags");

	Params::BP_GameMode_ConquestMode_C_RandomizeFlags Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewConquestFlagRef != nullptr)
		*NewConquestFlagRef = Parms.NewConquestFlagRef;
}


// Function BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C.GrantPlayerResources
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Character_C*                  Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GameMode_ConquestMode_C::GrantPlayerResources(class ABP_Character_C* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GameMode_ConquestMode_C", "GrantPlayerResources");

	Params::BP_GameMode_ConquestMode_C_GrantPlayerResources Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
