#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameMode_ConquestMode

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ST_ShipSpawnQueue_renamed_structs.hpp"
#include "BP_CoreGameMode_classes.hpp"
#include "E_Items_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GameMode_ConquestMode.BP_GameMode_ConquestMode_C
// 0x0060 (0x06D0 - 0x0670)
class ABP_GameMode_ConquestMode_C final : public ABP_CoreGameMode_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_GameMode_ConquestMode_C;         // 0x0670(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         RedFleetCrews;                                     // 0x0678(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BlueFleetCrews;                                    // 0x067C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class ABP_ConquestFlag_C*>             AllConquestFlags;                                  // 0x0680(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	TArray<class ABP_ConquestBoatSpawn_C*>        AllShipSpawnsUnchanged;                            // 0x0690(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	TArray<struct FST_ShipSpawnQueue_renamed>     ShipsToSpawn;                                      // 0x06A0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	int32                                         ShipCueueShipToRemove;                             // 0x06B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          NewShipSpawned;                                    // 0x06B4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_6B5[0x3];                                      // 0x06B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         MaxTicketsPerTeam;                                 // 0x06B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         TicketDepletionAmount;                             // 0x06BC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         FlagTicketReductionDelay;                          // 0x06C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         SpawnAtWreckTime;                                  // 0x06C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_ConquestFlag_C*                     CurrentFlag;                                       // 0x06C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_GameMode_ConquestMode(int32 EntryPoint);
	void EndConquestMatchEvent(int32 WinningFleet);
	void TeamCreatedEvent(int32 TeamID);
	void StartGameEvent_TickingEvent_();
	void K2_OnLogout(class AController* ExitingController);
	void ReceiveTick(float DeltaSeconds);
	void K2_PostLogin(class APlayerController* NewPlayer);
	void ReceiveBeginPlay();
	void StartConquestMatch();
	void GetRandomFleetSpawnPoint(int32 Fleet, TArray<class ABP_ConquestBoatSpawn_C*>& RemainingSpawnPoints);
	void SortTeamInFleet(int32 TeamID);
	void EndConquestMatch(int32 WinningFleet);
	void GetRandomFleetSpawnPointMidMatch(int32 Fleet, class ABP_ConquestBoatSpawn_C** SpawnPoint, bool* Success);
	void AddShipToSpawnQueue(int32 FleetID, int32 TeamID, class UClass* ShipClass_0);
	void AddInitialResourcesToShip(class ABP_BoatMeshBase_C* ShipRef);
	void FullyUpgradeShip(class ABP_BoatMeshBase_C* ShipRef);
	void RandomizeFlags(class ABP_ConquestFlag_C** NewConquestFlagRef);
	void GrantPlayerResources(class ABP_Character_C* Character);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GameMode_ConquestMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GameMode_ConquestMode_C")
	}
	static class ABP_GameMode_ConquestMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GameMode_ConquestMode_C>();
	}
};
DUMPER7_ASSERTS_ABP_GameMode_ConquestMode_C;

SDK_NAMESPACE_END
