#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Lootcrate

#include "Basic.hpp"

#include "BP_Lootcrate_classes.hpp"
#include "BP_Lootcrate_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Lootcrate.BP_Lootcrate_C.ExecuteUbergraph_BP_Lootcrate
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Lootcrate_C::ExecuteUbergraph_BP_Lootcrate(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lootcrate_C", "ExecuteUbergraph_BP_Lootcrate");

	Params::BP_Lootcrate_C_ExecuteUbergraph_BP_Lootcrate Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Lootcrate.BP_Lootcrate_C.BreakCrateLocally
// (BlueprintCallable, BlueprintEvent)

void ABP_Lootcrate_C::BreakCrateLocally()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lootcrate_C", "BreakCrateLocally");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Lootcrate.BP_Lootcrate_C.MC_BreakCrate
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_Lootcrate_C::MC_BreakCrate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lootcrate_C", "MC_BreakCrate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Lootcrate.BP_Lootcrate_C.BreakCrate
// (BlueprintCallable, BlueprintEvent)

void ABP_Lootcrate_C::BreakCrate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lootcrate_C", "BreakCrate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Lootcrate.BP_Lootcrate_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Lootcrate_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lootcrate_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Lootcrate.BP_Lootcrate_C.OnRep_Broken
// (BlueprintCallable, BlueprintEvent)

void ABP_Lootcrate_C::OnRep_Broken()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lootcrate_C", "OnRep_Broken");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Lootcrate.BP_Lootcrate_C.BreakLootCrate
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Lootcrate_C::BreakLootCrate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lootcrate_C", "BreakLootCrate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Lootcrate.BP_Lootcrate_C.SpawnItemWithRaycast
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Lootcrate_C::SpawnItemWithRaycast(const struct FVector& Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Lootcrate_C", "SpawnItemWithRaycast");

	Params::BP_Lootcrate_C_SpawnItemWithRaycast Parms{};

	Parms.Location = std::move(Location);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
