#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupWeaponBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "E_EquipmentSlots_structs.hpp"
#include "BP_PickupBase_classes.hpp"
#include "E_NewWeaponStates_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PickupWeaponBase.BP_PickupWeaponBase_C
// 0x0020 (0x03F0 - 0x03D0)
class ABP_PickupWeaponBase_C : public ABP_PickupBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_PickupWeaponBase_C;              // 0x03D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         WeaponID;                                          // 0x03D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         DefaultAmmoAmount;                                 // 0x03DC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_EquipmentSlots                              WeaponType;                                        // 0x03E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_NewWeaponStates                             NewWeapon;                                         // 0x03E1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_3E2[0x6];                                      // 0x03E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_Character_C*                        Real_Interacting_Character_Ref;                    // 0x03E8(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_PickupWeaponBase(int32 EntryPoint);
	void S_Force_Interactive_Character_Ref(class ABP_Character_C* Character_Ref);
	void Refresh_materials();
	void TakePickupLocal();
	void TakePickup();
	void ReceiveBeginPlay();
	void UserConstructionScript();
	void OnRep_Real_Interacting_Character_Ref();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PickupWeaponBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PickupWeaponBase_C")
	}
	static class ABP_PickupWeaponBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PickupWeaponBase_C>();
	}
};
DUMPER7_ASSERTS_ABP_PickupWeaponBase_C;

SDK_NAMESPACE_END
