#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ProjectileMultiCrossbowArrow

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_ProjectileMultiCrossbowArrow.BP_ProjectileMultiCrossbowArrow_C.ExecuteUbergraph_BP_ProjectileMultiCrossbowArrow
// 0x0008 (0x0008 - 0x0000)
struct BP_ProjectileMultiCrossbowArrow_C_ExecuteUbergraph_BP_ProjectileMultiCrossbowArrow final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_ForceKilled_;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_ProjectileMultiCrossbowArrow_C_ExecuteUbergraph_BP_ProjectileMultiCrossbowArrow;

// Function BP_ProjectileMultiCrossbowArrow.BP_ProjectileMultiCrossbowArrow_C.PostHit
// 0x0001 (0x0001 - 0x0000)
struct BP_ProjectileMultiCrossbowArrow_C_PostHit final
{
public:
	bool                                          ForceKilled_;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_ProjectileMultiCrossbowArrow_C_PostHit;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
