#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupArrows

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_PickupArrows.BP_PickupArrows_C.ExecuteUbergraph_BP_PickupArrows
// 0x0004 (0x0004 - 0x0000)
struct BP_PickupArrows_C_ExecuteUbergraph_BP_PickupArrows final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_PickupArrows_C_ExecuteUbergraph_BP_PickupArrows;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
