#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupFishAMmo

#include "Basic.hpp"

#include "BP_PickupFishAMmo_classes.hpp"
#include "BP_PickupFishAMmo_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_PickupFishAMmo.BP_PickupFishAmmo_C.ExecuteUbergraph_BP_PickupFishAmmo
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PickupFishAmmo_C::ExecuteUbergraph_BP_PickupFishAmmo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PickupFishAmmo_C", "ExecuteUbergraph_BP_PickupFishAmmo");

	Params::BP_PickupFishAmmo_C_ExecuteUbergraph_BP_PickupFishAmmo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PickupFishAMmo.BP_PickupFishAmmo_C.S_Activate
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_PickupFishAmmo_C::S_Activate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PickupFishAmmo_C", "S_Activate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PickupFishAMmo.BP_PickupFishAmmo_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_PickupFishAmmo_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PickupFishAmmo_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
