#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Projectile_Repeater

#include "Basic.hpp"

#include "BP_ProjectileBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Projectile_Repeater.BP_Projectile_Repeater_C
// 0x0000 (0x0430 - 0x0430)
class ABP_Projectile_Repeater_C final : public ABP_ProjectileBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Projectile_Repeater_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Projectile_Repeater_C")
	}
	static class ABP_Projectile_Repeater_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Projectile_Repeater_C>();
	}
};
DUMPER7_ASSERTS_ABP_Projectile_Repeater_C;

SDK_NAMESPACE_END
