#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupGoldBox_High

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "E_TurnInTreasure_structs.hpp"
#include "BP_PickupBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PickupGoldBox_High.BP_PickupGoldBox_High_C
// 0x0038 (0x0408 - 0x03D0)
class ABP_PickupGoldBox_High_C : public ABP_PickupBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_PickupGoldBox_High_C;            // 0x03D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	E_TurnInTreasure                              ChestType;                                         // 0x03D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D9[0x3];                                      // 0x03D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Discovered;                                        // 0x03DC(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	bool                                          DiscoverySynced;                                   // 0x03E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          TeamIDSynced;                                      // 0x03E1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3E2[0x6];                                      // 0x03E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_IconBase_C*                         MarkerRef;                                         // 0x03E8(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DetachedFromShip;                                  // 0x03F0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)
	uint8                                         Pad_3F1[0x3];                                      // 0x03F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         GoldAmountToReward;                                // 0x03F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 IconWidget;                                        // 0x03F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Seen;                                              // 0x0400(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_PickupGoldBox_High(int32 EntryPoint);
	void Enable_Icon(int32 Team);
	void ReceiveDestroyed();
	void TeamIDChanged();
	void TakePickup();
	void Activate(class ABP_Character_C* LocalCharacterRef_0);
	void ReceiveTick(float DeltaSeconds);
	void ReceiveBeginPlay();
	void OnRep_Discovered();
	void OnRep_DetachedFromShip();
	void OnRep_GoldAmountToReward();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PickupGoldBox_High_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PickupGoldBox_High_C")
	}
	static class ABP_PickupGoldBox_High_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PickupGoldBox_High_C>();
	}
};
DUMPER7_ASSERTS_ABP_PickupGoldBox_High_C;

SDK_NAMESPACE_END
