#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupCloth

#include "Basic.hpp"

#include "BP_PickupItemBase_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PickupCloth.BP_PickupCloth_C
// 0x0008 (0x03E0 - 0x03D8)
class ABP_PickupCloth_C final : public ABP_PickupItemBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_PickupCloth_C;                   // 0x03D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_PickupCloth(int32 EntryPoint);
	void S_Activate();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PickupCloth_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PickupCloth_C")
	}
	static class ABP_PickupCloth_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PickupCloth_C>();
	}
};
DUMPER7_ASSERTS_ABP_PickupCloth_C;

SDK_NAMESPACE_END
