#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupGoldBox_ShipBox

#include "Basic.hpp"

#include "BP_PickupGoldBox_High_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PickupGoldBox_ShipBox.BP_PickupGoldBox_ShipBox_C
// 0x0000 (0x0408 - 0x0408)
class ABP_PickupGoldBox_ShipBox_C final : public ABP_PickupGoldBox_High_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PickupGoldBox_ShipBox_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PickupGoldBox_ShipBox_C")
	}
	static class ABP_PickupGoldBox_ShipBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PickupGoldBox_ShipBox_C>();
	}
};
DUMPER7_ASSERTS_ABP_PickupGoldBox_ShipBox_C;

SDK_NAMESPACE_END
