#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupBackpackUpgrade

#include "Basic.hpp"

#include "BP_PickupBackpackUpgrade_classes.hpp"
#include "BP_PickupBackpackUpgrade_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_PickupBackpackUpgrade.BP_PickupBackpackUpgrade_C.ExecuteUbergraph_BP_PickupBackpackUpgrade
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PickupBackpackUpgrade_C::ExecuteUbergraph_BP_PickupBackpackUpgrade(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PickupBackpackUpgrade_C", "ExecuteUbergraph_BP_PickupBackpackUpgrade");

	Params::BP_PickupBackpackUpgrade_C_ExecuteUbergraph_BP_PickupBackpackUpgrade Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PickupBackpackUpgrade.BP_PickupBackpackUpgrade_C.S_Activate
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABP_PickupBackpackUpgrade_C::S_Activate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PickupBackpackUpgrade_C", "S_Activate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PickupBackpackUpgrade.BP_PickupBackpackUpgrade_C.Activate
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Character_C*                  LocalCharacterRef_0                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PickupBackpackUpgrade_C::Activate(class ABP_Character_C* LocalCharacterRef_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PickupBackpackUpgrade_C", "Activate");

	Params::BP_PickupBackpackUpgrade_C_Activate Parms{};

	Parms.LocalCharacterRef_0 = LocalCharacterRef_0;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
