#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PaintSpray

#include "Basic.hpp"

#include "BP_PaintSpray_classes.hpp"
#include "BP_PaintSpray_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_PaintSpray.BP_PaintSpray_C.ExecuteUbergraph_BP_PaintSpray
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PaintSpray_C::ExecuteUbergraph_BP_PaintSpray(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PaintSpray_C", "ExecuteUbergraph_BP_PaintSpray");

	Params::BP_PaintSpray_C_ExecuteUbergraph_BP_PaintSpray Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PaintSpray.BP_PaintSpray_C.Destroy Self
// (BlueprintCallable, BlueprintEvent)

void ABP_PaintSpray_C::Destroy_Self()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PaintSpray_C", "Destroy Self");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PaintSpray.BP_PaintSpray_C.SetEmblemAndColor
// (BlueprintCallable, BlueprintEvent)

void ABP_PaintSpray_C::SetEmblemAndColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PaintSpray_C", "SetEmblemAndColor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PaintSpray.BP_PaintSpray_C.Remove
// (BlueprintCallable, BlueprintEvent)

void ABP_PaintSpray_C::Remove()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PaintSpray_C", "Remove");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PaintSpray.BP_PaintSpray_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PaintSpray_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PaintSpray_C", "ReceiveTick");

	Params::BP_PaintSpray_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PaintSpray.BP_PaintSpray_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_PaintSpray_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PaintSpray_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PaintSpray.BP_PaintSpray_C.OnRep_Crew Manager
// (BlueprintCallable, BlueprintEvent)

void ABP_PaintSpray_C::OnRep_Crew_Manager()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PaintSpray_C", "OnRep_Crew Manager");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
