#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ProjectileHealingCrossbowArrow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ProjectileBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ProjectileHealingCrossbowArrow.BP_ProjectileHealingCrossbowArrow_C
// 0x0020 (0x0450 - 0x0430)
class ABP_ProjectileHealingCrossbowArrow_C final : public ABP_ProjectileBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_ProjectileHealingCrossbowArrow_C; // 0x0430(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UParticleSystemComponent*               P_HealingSmoke;                                    // 0x0438(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	int32                                         HealAmount;                                        // 0x0440(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         HealDuration;                                      // 0x0444(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Direct_Health_Amount;                              // 0x0448(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ProjectileHealingCrossbowArrow(int32 EntryPoint);
	void PostCharacterHit();
	void PostPlayerHit(class ABP_Character_C* HitPlayer, class ABP_Controller_C* Attacker);
	void PostHit(bool ForceKilled_);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ProjectileHealingCrossbowArrow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ProjectileHealingCrossbowArrow_C")
	}
	static class ABP_ProjectileHealingCrossbowArrow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ProjectileHealingCrossbowArrow_C>();
	}
};
DUMPER7_ASSERTS_ABP_ProjectileHealingCrossbowArrow_C;

SDK_NAMESPACE_END
