#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ProjectileHealingCrossbowArrow

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_ProjectileHealingCrossbowArrow.BP_ProjectileHealingCrossbowArrow_C.ExecuteUbergraph_BP_ProjectileHealingCrossbowArrow
// 0x0018 (0x0018 - 0x0000)
struct BP_ProjectileHealingCrossbowArrow_C_ExecuteUbergraph_BP_ProjectileHealingCrossbowArrow final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_ForceKilled_;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_Character_C*                        K2Node_Event_HitPlayer;                            // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_Controller_C*                       K2Node_Event_Attacker;                             // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_ProjectileHealingCrossbowArrow_C_ExecuteUbergraph_BP_ProjectileHealingCrossbowArrow;

// Function BP_ProjectileHealingCrossbowArrow.BP_ProjectileHealingCrossbowArrow_C.PostPlayerHit
// 0x0010 (0x0010 - 0x0000)
struct BP_ProjectileHealingCrossbowArrow_C_PostPlayerHit final
{
public:
	class ABP_Character_C*                        HitPlayer;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_Controller_C*                       Attacker;                                          // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_ProjectileHealingCrossbowArrow_C_PostPlayerHit;

// Function BP_ProjectileHealingCrossbowArrow.BP_ProjectileHealingCrossbowArrow_C.PostHit
// 0x0001 (0x0001 - 0x0000)
struct BP_ProjectileHealingCrossbowArrow_C_PostHit final
{
public:
	bool                                          ForceKilled_;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_ProjectileHealingCrossbowArrow_C_PostHit;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
