#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ProjectileDualFlintlock

#include "Basic.hpp"

#include "BP_ProjectileBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ProjectileDualFlintlock.BP_ProjectileDualFlintlock_C
// 0x0000 (0x0430 - 0x0430)
class ABP_ProjectileDualFlintlock_C final : public ABP_ProjectileBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ProjectileDualFlintlock_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ProjectileDualFlintlock_C")
	}
	static class ABP_ProjectileDualFlintlock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ProjectileDualFlintlock_C>();
	}
};
DUMPER7_ASSERTS_ABP_ProjectileDualFlintlock_C;

SDK_NAMESPACE_END
