#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupItemBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_PickupBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PickupItemBase.BP_PickupItemBase_C
// 0x0008 (0x03D8 - 0x03D0)
class ABP_PickupItemBase_C : public ABP_PickupBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_PickupItemBase_C;                // 0x03D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_PickupItemBase(int32 EntryPoint);
	void TakePickupLocal();
	void TakePickup();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PickupItemBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PickupItemBase_C")
	}
	static class ABP_PickupItemBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PickupItemBase_C>();
	}
};
DUMPER7_ASSERTS_ABP_PickupItemBase_C;

SDK_NAMESPACE_END
