#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ProjectileFish

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ProjectileBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ProjectileFish.BP_ProjectileFish_C
// 0x0008 (0x0438 - 0x0430)
class ABP_ProjectileFish_C final : public ABP_ProjectileBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_ProjectileFish_C;                // 0x0430(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_ProjectileFish(int32 EntryPoint);
	void PostHit(bool ForceKilled_);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ProjectileFish_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ProjectileFish_C")
	}
	static class ABP_ProjectileFish_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ProjectileFish_C>();
	}
};
DUMPER7_ASSERTS_ABP_ProjectileFish_C;

SDK_NAMESPACE_END
