#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupGoldBox_Super

#include "Basic.hpp"

#include "BP_PickupGoldBox_High_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PickupGoldBox_Super.BP_PickupGoldBox_Super_C
// 0x0008 (0x0410 - 0x0408)
class ABP_PickupGoldBox_Super_C final : public ABP_PickupGoldBox_High_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_PickupGoldBox_Super_C;           // 0x0408(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_PickupGoldBox_Super(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PickupGoldBox_Super_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PickupGoldBox_Super_C")
	}
	static class ABP_PickupGoldBox_Super_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PickupGoldBox_Super_C>();
	}
};
DUMPER7_ASSERTS_ABP_PickupGoldBox_Super_C;

SDK_NAMESPACE_END
