#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupWeaponHuntingBow

#include "Basic.hpp"

#include "BP_PickupWeaponBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PickupWeaponHuntingBow.BP_PickupWeaponHuntingBow_C
// 0x0000 (0x03F0 - 0x03F0)
class ABP_PickupWeaponHuntingBow_C final : public ABP_PickupWeaponBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PickupWeaponHuntingBow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PickupWeaponHuntingBow_C")
	}
	static class ABP_PickupWeaponHuntingBow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PickupWeaponHuntingBow_C>();
	}
};
DUMPER7_ASSERTS_ABP_PickupWeaponHuntingBow_C;

SDK_NAMESPACE_END
