#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ProjectileExplosiveArrow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ProjectileBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ProjectileExplosiveArrow.BP_ProjectileExplosiveArrow_C
// 0x0010 (0x0440 - 0x0430)
class ABP_ProjectileExplosiveArrow_C final : public ABP_ProjectileBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_ProjectileExplosiveArrow_C;      // 0x0430(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UParticleSystemComponent*               ParticleSystem_0;                                  // 0x0438(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ProjectileExplosiveArrow(int32 EntryPoint);
	void PostHit(bool ForceKilled_);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ProjectileExplosiveArrow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ProjectileExplosiveArrow_C")
	}
	static class ABP_ProjectileExplosiveArrow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ProjectileExplosiveArrow_C>();
	}
};
DUMPER7_ASSERTS_ABP_ProjectileExplosiveArrow_C;

SDK_NAMESPACE_END
