#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupWeaponRepeater

#include "Basic.hpp"

#include "BP_PickupWeaponRepeater_classes.hpp"
#include "BP_PickupWeaponRepeater_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_PickupWeaponRepeater.BP_PickupWeaponRepeater_C.ExecuteUbergraph_BP_PickupWeaponRepeater
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PickupWeaponRepeater_C::ExecuteUbergraph_BP_PickupWeaponRepeater(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PickupWeaponRepeater_C", "ExecuteUbergraph_BP_PickupWeaponRepeater");

	Params::BP_PickupWeaponRepeater_C_ExecuteUbergraph_BP_PickupWeaponRepeater Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PickupWeaponRepeater.BP_PickupWeaponRepeater_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PickupWeaponRepeater_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PickupWeaponRepeater_C", "ReceiveTick");

	Params::BP_PickupWeaponRepeater_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
