#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PickupExplosiveBarrel

#include "Basic.hpp"

#include "BP_PickupExplosiveBarrel_classes.hpp"
#include "BP_PickupExplosiveBarrel_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_PickupExplosiveBarrel.BP_PickupExplosiveBarrel_C.ExecuteUbergraph_BP_PickupExplosiveBarrel
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PickupExplosiveBarrel_C::ExecuteUbergraph_BP_PickupExplosiveBarrel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PickupExplosiveBarrel_C", "ExecuteUbergraph_BP_PickupExplosiveBarrel");

	Params::BP_PickupExplosiveBarrel_C_ExecuteUbergraph_BP_PickupExplosiveBarrel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PickupExplosiveBarrel.BP_PickupExplosiveBarrel_C.S_Explode
// (BlueprintCallable, BlueprintEvent)

void ABP_PickupExplosiveBarrel_C::S_Explode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PickupExplosiveBarrel_C", "S_Explode");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PickupExplosiveBarrel.BP_PickupExplosiveBarrel_C.MC_Effects
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_PickupExplosiveBarrel_C::MC_Effects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PickupExplosiveBarrel_C", "MC_Effects");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PickupExplosiveBarrel.BP_PickupExplosiveBarrel_C.Explode
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Controller_C*                 ControllerRef                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   DetonationDelay                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PickupExplosiveBarrel_C::Explode(class ABP_Controller_C* ControllerRef, float DetonationDelay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PickupExplosiveBarrel_C", "Explode");

	Params::BP_PickupExplosiveBarrel_C_Explode Parms{};

	Parms.ControllerRef = ControllerRef;
	Parms.DetonationDelay = DetonationDelay;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
