#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_QuickAccesPoint_AntiCannonball

#include "Basic.hpp"

#include "BP_QuickAccesPoint_AntiCannonball_classes.hpp"
#include "BP_QuickAccesPoint_AntiCannonball_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_QuickAccesPoint_AntiCannonball.BP_QuickAccesPoint_AntiCannonball_C.ExecuteUbergraph_BP_QuickAccesPoint_AntiCannonball
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_QuickAccesPoint_AntiCannonball_C::ExecuteUbergraph_BP_QuickAccesPoint_AntiCannonball(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuickAccesPoint_AntiCannonball_C", "ExecuteUbergraph_BP_QuickAccesPoint_AntiCannonball");

	Params::BP_QuickAccesPoint_AntiCannonball_C_ExecuteUbergraph_BP_QuickAccesPoint_AntiCannonball Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_QuickAccesPoint_AntiCannonball.BP_QuickAccesPoint_AntiCannonball_C.AmountRepEvent
// (BlueprintCallable, BlueprintEvent)

void ABP_QuickAccesPoint_AntiCannonball_C::AmountRepEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuickAccesPoint_AntiCannonball_C", "AmountRepEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuickAccesPoint_AntiCannonball.BP_QuickAccesPoint_AntiCannonball_C.GiveResources
// (BlueprintCallable, BlueprintEvent)

void ABP_QuickAccesPoint_AntiCannonball_C::GiveResources()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuickAccesPoint_AntiCannonball_C", "GiveResources");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_QuickAccesPoint_AntiCannonball.BP_QuickAccesPoint_AntiCannonball_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_QuickAccesPoint_AntiCannonball_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_QuickAccesPoint_AntiCannonball_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
