#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RandomWeaponSpawnPoint

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_RandomWeaponSpawnPoint.BP_RandomWeaponSpawnPoint_C
// 0x0028 (0x0248 - 0x0220)
class ABP_RandomWeaponSpawnPoint_C final : public AActor
{
public:
	class UBillboardComponent*                    Billboard;                                         // 0x0220(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        Arrow;                                             // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Cylinder;                                          // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          WeaponRespawns;                                    // 0x0240(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_241[0x3];                                      // 0x0241(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         RespawnTime;                                       // 0x0244(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RandomWeaponSpawnPoint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RandomWeaponSpawnPoint_C")
	}
	static class ABP_RandomWeaponSpawnPoint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RandomWeaponSpawnPoint_C>();
	}
};
DUMPER7_ASSERTS_ABP_RandomWeaponSpawnPoint_C;

SDK_NAMESPACE_END
