#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SwivelPosition

#include "Basic.hpp"

#include "BP_SwivelPosition_classes.hpp"
#include "BP_SwivelPosition_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_SwivelPosition.BP_SwivelPosition_C.ExecuteUbergraph_BP_SwivelPosition
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SwivelPosition_C::ExecuteUbergraph_BP_SwivelPosition(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SwivelPosition_C", "ExecuteUbergraph_BP_SwivelPosition");

	Params::BP_SwivelPosition_C_ExecuteUbergraph_BP_SwivelPosition Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SwivelPosition.BP_SwivelPosition_C.MC_MountEffects
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_SwivelPosition_C::MC_MountEffects()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SwivelPosition_C", "MC_MountEffects");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SwivelPosition.BP_SwivelPosition_C.MountSwivel
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_SwivelPosition_C::MountSwivel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SwivelPosition_C", "MountSwivel");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
