#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SteeringWheelKick

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_InteractableBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SteeringWheelKick.BP_SteeringWheelKick_C
// 0x0010 (0x0330 - 0x0320)
class ABP_SteeringWheelKick_C final : public ABP_InteractableBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_SteeringWheelKick_C;             // 0x0320(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          KickPlayer;                                        // 0x0328(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_SteeringWheelKick(int32 EntryPoint);
	void EngageFromServer(class AAlpha_PlayerController_C* Interacting_Controller);
	void StopActivate();
	void Activate(class ABP_Character_C* LocalCharacterRef);
	void MC_KickEffects();
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SteeringWheelKick_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SteeringWheelKick_C")
	}
	static class ABP_SteeringWheelKick_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SteeringWheelKick_C>();
	}
};
DUMPER7_ASSERTS_ABP_SteeringWheelKick_C;

SDK_NAMESPACE_END
