#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Seaguls

#include "Basic.hpp"

#include "BP_Seaguls_classes.hpp"
#include "BP_Seaguls_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Seaguls.BP_Seaguls_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Seaguls_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Seaguls_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Seaguls.BP_Seaguls_C.ExecuteUbergraph_BP_Seaguls
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Seaguls_C::ExecuteUbergraph_BP_Seaguls(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Seaguls_C", "ExecuteUbergraph_BP_Seaguls");

	Params::BP_Seaguls_C_ExecuteUbergraph_BP_Seaguls Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
