#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ShipWaterCulling

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_ShipWaterCulling.BP_ShipWaterCulling_C.ExecuteUbergraph_BP_ShipWaterCulling
// 0x0008 (0x0008 - 0x0000)
struct BP_ShipWaterCulling_C_ExecuteUbergraph_BP_ShipWaterCulling final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_Show;                           // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_ShipWaterCulling_C_ExecuteUbergraph_BP_ShipWaterCulling;

// Function BP_ShipWaterCulling.BP_ShipWaterCulling_C.ShowCulling
// 0x0001 (0x0001 - 0x0000)
struct BP_ShipWaterCulling_C_ShowCulling final
{
public:
	bool                                          Show;                                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BP_ShipWaterCulling_C_ShowCulling;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
