#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SoundTester

#include "Basic.hpp"

#include "BP_SoundTester_classes.hpp"
#include "BP_SoundTester_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_SoundTester.BP_SoundTester_C.ExecuteUbergraph_BP_SoundTester
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SoundTester_C::ExecuteUbergraph_BP_SoundTester(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SoundTester_C", "ExecuteUbergraph_BP_SoundTester");

	Params::BP_SoundTester_C_ExecuteUbergraph_BP_SoundTester Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SoundTester.BP_SoundTester_C.PlayTestSound
// (BlueprintCallable, BlueprintEvent)

void ABP_SoundTester_C::PlayTestSound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SoundTester_C", "PlayTestSound");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
