#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UIArrow_CaptureFlag

#include "Basic.hpp"

#include "BP_UIArrow_CaptureFlag_classes.hpp"
#include "BP_UIArrow_CaptureFlag_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_UIArrow_CaptureFlag.BP_UIArrow_CaptureFlag_C.ExecuteUbergraph_BP_UIArrow_CaptureFlag
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UIArrow_CaptureFlag_C::ExecuteUbergraph_BP_UIArrow_CaptureFlag(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UIArrow_CaptureFlag_C", "ExecuteUbergraph_BP_UIArrow_CaptureFlag");

	Params::BP_UIArrow_CaptureFlag_C_ExecuteUbergraph_BP_UIArrow_CaptureFlag Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UIArrow_CaptureFlag.BP_UIArrow_CaptureFlag_C.Set Flag Reference
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_ConquestFlag_C*               Flag_Ref                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_UIArrow_CaptureFlag_C::Set_Flag_Reference(class ABP_ConquestFlag_C* Flag_Ref)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UIArrow_CaptureFlag_C", "Set Flag Reference");

	Params::BP_UIArrow_CaptureFlag_C_Set_Flag_Reference Parms{};

	Parms.Flag_Ref = Flag_Ref;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UIArrow_CaptureFlag.BP_UIArrow_CaptureFlag_C.Adjust2DWidgetAdvanced
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_UIArrow_CaptureFlag_C::Adjust2DWidgetAdvanced()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UIArrow_CaptureFlag_C", "Adjust2DWidgetAdvanced");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UIArrow_CaptureFlag.BP_UIArrow_CaptureFlag_C.Adjust3DWidgetAdvanced
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_UIArrow_CaptureFlag_C::Adjust3DWidgetAdvanced()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UIArrow_CaptureFlag_C", "Adjust3DWidgetAdvanced");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UIArrow_CaptureFlag.BP_UIArrow_CaptureFlag_C.InitializeWidgetValues
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_UIArrow_CaptureFlag_C::InitializeWidgetValues()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UIArrow_CaptureFlag_C", "InitializeWidgetValues");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UIArrow_CaptureFlag.BP_UIArrow_CaptureFlag_C.ShouldShow
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   Param_ShouldShow_0                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_UIArrow_CaptureFlag_C::ShouldShow(bool* Param_ShouldShow_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UIArrow_CaptureFlag_C", "ShouldShow");

	Params::BP_UIArrow_CaptureFlag_C_ShouldShow Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ShouldShow_0 != nullptr)
		*Param_ShouldShow_0 = Parms.Param_ShouldShow_0;
}


// Function BP_UIArrow_CaptureFlag.BP_UIArrow_CaptureFlag_C.ShouldShow3D
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   Param_ShouldShow3D_0                                   (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_UIArrow_CaptureFlag_C::ShouldShow3D(bool* Param_ShouldShow3D_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UIArrow_CaptureFlag_C", "ShouldShow3D");

	Params::BP_UIArrow_CaptureFlag_C_ShouldShow3D Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_ShouldShow3D_0 != nullptr)
		*Param_ShouldShow3D_0 = Parms.Param_ShouldShow3D_0;
}


SDK_NAMESPACE_END
