#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WeaponBow

#include "Basic.hpp"

#include "BP_WeaponBow_classes.hpp"
#include "BP_WeaponBow_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_WeaponBow.BP_WeaponBow_C.ExecuteUbergraph_BP_WeaponBow
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_WeaponBow_C::ExecuteUbergraph_BP_WeaponBow(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WeaponBow_C", "ExecuteUbergraph_BP_WeaponBow");

	Params::BP_WeaponBow_C_ExecuteUbergraph_BP_WeaponBow Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_WeaponBow.BP_WeaponBow_C.LoadedState
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_WeaponBow_C::LoadedState(bool Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_WeaponBow_C", "LoadedState");

	Params::BP_WeaponBow_C_LoadedState Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
